### ISSUE TITLE
基于开源的diff，patch类库，构建一个Android增量升级方案。

### ISSUE THREAD

**Issue by snowdream** [snowdream/ideas#1]
1. 基于 HDiffPatch ，bsdiff等，通过jni封装成so库以及nodejs类库；
1. 基于expressjs构建一个简单的平台服务，使用nodejs版本的类库，来创建patch包；
1. 基于so库，创建一个android类库，完成支持增量升级的自动更新方案。

参考链接：
1. http://blog.csdn.net/housisong/article/details/9003013
1. https://github.com/sisong/HDiffPatch
1. http://blog.csdn.net/hmg25/article/details/8100896
1. https://github.com/mendsley/bsdiff
1. https://github.com/CankingApp/SmartUpdate
1. http://www.daemonology.net/bsdiff/
1. http://www.oschina.net/code/snippet_54100_7331
1. http://hcq0618.blog.163.com/blog/static/17809035120135273658986/
1. http://blog.csdn.net/tu_bingbing/article/details/8538592#
1. https://github.com/cundong/SmartAppUpdates
1. https://github.com/xmikos/setools-android/tree/master/jni/libqpol/bzip2
1. https://github.com/cundong/SmartAppUpdates/tree/master/ApkPatchLibraryServer/jni/bzip2
1. http://blog.csdn.net/brok1n/article/details/50406774
1. https://github.com/JackCho/AndroidPatchUpdate/tree/master/jni

**Comment by mikewang0326** [comment]
Great ！

**Comment by snowdream** [comment]
工作积累之NDK编译STL  http://blog.csdn.net/startwithdp/article/details/7050732

**Comment by snowdream** [comment]
https://github.com/snowdream/android-diffpatch
